import "./index.less";
import { msgOption, alertParameter, openParameter, modalParameter } from "./type";
declare class stlLayer {
    times: number;
    iconfontSrc: string;
    iconList: any;
    iconColorList: any;
    msgObj: any;
    hasTitleAlertObj: any;
    noTitleAlertObj: any;
    alertObj: any;
    openObj: any;
    modalObj: any;
    bgDom: HTMLElement;
    closeCallback: (e: any) => void;
    alertBtnCallback: (e: any) => void;
    constructor();
    private getBgDom;
    private getDomStr;
    private getIconStr;
    private getCloseStr;
    private msgStr;
    msg(content: string, options?: msgOption, end?: () => void): void;
    private hasTitleAlertStr;
    private noTitleAlertStr;
    private addAlertBtnEvent;
    alert(obj: alertParameter): void;
    private getOpenStr;
    open(data: openParameter): void;
    private getModalFn;
    modal(data: modalParameter): void;
    private addBgEvent;
    private addOpenBtnFn;
    private addCloseEventFn;
    private closeFn;
    private appendDom;
    private autoClose;
}
export declare let layer: stlLayer;
export {};
