import "./index.less";
import { option } from "./type";
export declare class imageSlider {
    private option;
    private sliderLength;
    private totalDistance;
    private sportTimeout;
    private intervalTimeout;
    private propertyName;
    private step;
    private sportSetTimeoutFn;
    private startSportFn;
    private timer;
    private nowClass;
    private parentSize;
    private directionType;
    private oneDistance;
    private isChangeSport;
    private changeType;
    private index;
    private translateVal;
    private nowDistance;
    private distance;
    private mouseKey;
    private distanceNumber;
    private nowDistanceNumber;
    private $parent;
    private $sliderDom;
    private $sliderList;
    private $itemList;
    private $prevDom;
    private $nextDom;
    constructor(option: option);
    private initOption;
    private getDom;
    private getSliderList;
    private getExerciseValue;
    getDistance(end?: number | string): number;
    private addDom;
    private getBtn;
    private cloneFn;
    private sportFn;
    private intervalsFn;
    private calculateDistance;
    private intervalSportFn;
    private ordinarySportFn;
    updateIndex(index?: string | number): void;
    afterSportFn(type: string, fn: () => void): void;
    private cleatTimeoutFn;
    private changeFn;
    private clickInitFn;
    private addEventFn;
}
